before_install:
  - "script/clone_all_rspec_repos"
  # Downgrade bundler to work around https://github.com/bundler/bundler/issues/3004
  - gem install bundler -v=1.5.3
  - alias bundle="bundle _1.5.3_"
bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
script: "script/run_build"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head
  - ree
  - jruby-18mode
  - jruby
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
    # Until https://github.com/travis-ci/travis-ci/issues/2220 is fixed
    - rvm: 2.1.0
  fast_finish: true
